### ISSUE TITLE
Story:100 - Login Functionality User Service

### ISSUE THREAD

**Issue by teamSupprt** [Team-Talent-Zone/REPO_SERVICEAPI_v1.0#5]
Acceptance Criteria

When :

Login with username and password in GET method return user entity .

On success : return status code and return JSON user entity object output

On failure : return status code with error message as output

**Comment by teamSupprt** [comment]
login with user is not working getting HTTP error code on UI

**Comment by ismohammad** [comment]
bug is resolved , please test

**Comment by teamSupprt** [comment]
all good thanks
